import { Check, ShieldCheck, Sparkles } from "lucide-react"
import { Link } from "react-router-dom"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/src/components/ui/card"

const features = ["Transações e categorias ilimitadas", "Relatórios completos em PDF", "Sincronização segura na nuvem", "Novos recursos antecipadamente"]

export function Plan() {
  return <main className="mx-auto max-w-3xl space-y-8 pb-12"><header><p className="text-sm font-semibold text-[#00aa5c] dark:text-[#00ff88]">PLANOS</p><h1 className="mt-1 text-3xl font-bold">Matrix Finance Pro</h1><p className="mt-2 text-muted-foreground">O checkout está temporariamente indisponível enquanto concluímos a integração segura com o provedor de pagamentos.</p></header><Card className="glass-card border-[#00ff88]/20"><CardHeader><div className="flex items-center justify-between gap-4"><div><CardTitle className="flex items-center gap-2 text-2xl"><Sparkles className="h-5 w-5 text-[#00ff88]" aria-hidden="true" />Plano Pro</CardTitle><CardDescription className="mt-2">Acesso completo aos recursos avançados.</CardDescription></div><div className="text-right"><div className="text-3xl font-bold">R$ 29,90</div><div className="text-xs text-muted-foreground">por mês</div></div></div></CardHeader><CardContent><ul className="grid gap-3 sm:grid-cols-2">{features.map((feature) => <li key={feature} className="flex items-center gap-2 text-sm"><Check className="h-4 w-4 text-[#00ff88]" aria-hidden="true" />{feature}</li>)}</ul><div className="mt-8 flex items-start gap-3 rounded-xl border border-blue-500/20 bg-blue-500/5 p-4 text-sm text-muted-foreground"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-blue-400" aria-hidden="true" /><p>Nenhum plano será ativado sem confirmação real do pagamento pelo servidor. Seus dados e sua cobrança permanecem protegidos.</p></div></CardContent><CardFooter className="flex flex-col gap-3 sm:flex-row"><button type="button" disabled className="h-11 flex-1 cursor-not-allowed rounded-xl bg-muted px-4 text-sm font-semibold text-muted-foreground">Checkout em breve</button><Link to="/subscription" className="inline-flex h-11 flex-1 items-center justify-center rounded-xl border border-border text-sm font-medium hover:bg-muted">Ver minha assinatura</Link></CardFooter></Card></main>
}
